name: Improvement Feedback
description: Suggest improvements to existing features
title: "[Improvement]: "
labels: ["improvement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve! Share your feedback on existing features.

  - type: dropdown
    id: area
    attributes:
      label: Area of Improvement
      description: Which area does this improvement relate to?
      options:
        - UI/UX
        - Performance
        - Accessibility
        - Documentation
        - Code Quality
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: Describe how the feature currently works.
      placeholder: Currently, the feature...
    validations:
      required: true

  - type: textarea
    id: improvement
    attributes:
      label: Suggested Improvement
      description: Describe how you think it could be improved.
      placeholder: It would be better if...
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefits would this improvement provide?
      placeholder: This would help by...
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples or references from other tools/extensions.
      placeholder: Similar to how [tool] does it...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups.
      placeholder: Any additional information...
    validations:
      required: false
